#!/usr/bin/env python
import matplotlib
from scipy import signal
import matplotlib.pyplot as plt
import numpy as np
from pylab import *
matplotlib.use('Qt5Cairo')

m= 1
M= 5
L= 2
g= -9.81
d= 1
b= -1

A = np.array([ [0, 1, 0, 0],
               [0, -d/M, (b*m*g)/M, 0],
               [0, 0, 0, 1],
               [0, (-b*d)/(M*L), -(b*(m+M)*g)/(M*L), 0]])

B = np.array([[0],
              [1/M],
              [0],
              [b/(M*L)]])

C = np.array([1, 0, 0, 0])

D = np.array([0])

sis_esp_est= signal.StateSpace(A, B, C, D)
f = logspace(-2, 2, 1000)
w = 2 * pi * f
w, mag, phase = signal.bode(sis_esp_est, w)

plt.figure()
plt.semilogx(w/(2*pi), mag) # Gráfica de la magnitud de Bode
plt.ylim([-100, 4])
plt.xlabel('Frequency (Hz)')
plt.ylabel('Magnitude (dB)')

plt.figure()
plt.semilogx(w/(2*pi), phase) # Gráfica de fase de Bode
plt.xlabel('Frequency (Hz)')
plt.ylabel('Phase (degrees)')

plt.show()
